fail_fast: true
repos:
-   repo: local
    hooks:
    - id: system
      name: flake8
      entry: flake8
      pass_filenames: false
      language: system

-   repo: local
    hooks:
    - id: system
      name: isort
      entry: isort plynx
      pass_filenames: false
      language: system

-   repo: local
    hooks:
    - id: system
      name: pylint
      entry: pylint plynx
      pass_filenames: false
      language: system
