fail_fast: true
repos:
-   repo: local
    hooks:
    - id: system
      name: $ flake8
      entry: flake8 plynx
      pass_filenames: false
      language: system

-   repo: local
    hooks:
    - id: system
      name: $ isort plynx
      entry: isort plynx
      pass_filenames: false
      language: system

-   repo: local
    hooks:
    - id: system
      name: $ mypy plynx --ignore-missing-imports
      entry: mypy plynx --ignore-missing-imports
      pass_filenames: false
      language: system

-   repo: local
    hooks:
    - id: system
      name: $ pylint --disable=F0401 plynx
      entry: pylint --disable=F0401 plynx
      pass_filenames: false
      language: system
