version: "3.3"
services:
    mongodb:
        image: mongo:4.2.8
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet

    master:
        image: plynxteam/backend:latest
        container_name: "master"
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./data:/data
            - ./config.yaml:/app/config.yaml
        environment:
            - PLYNX_CONFIG=/app/config.yaml
        command: plynx worker -vvv -e basic-dag-workflow

    workers:
        image: plynxteam/backend:latest
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./data:/data
            - ./config.yaml:/app/config.yaml
        environment:
            - PLYNX_CONFIG=/app/config.yaml
        command: plynx worker -vvv -e basic-bash-jinja2-operation -e basic-python-node-operation -e basic-dag-operation

    api:
        image: plynxteam/backend:latest
        container_name: "api"
        ports:
            - "5005:5005"
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./data:/data
            - ./config.yaml:/app/config.yaml
        environment:
            - PLYNX_CONFIG=/app/config.yaml
        command: plynx api -vvv

    frontend:
        image: plynxteam/ui:latest
        container_name: "frontend"
        ports:
            - "3001:80"
        depends_on:
            - api
        links:
            - api
