class FileTypes:
    FILE = 'file'
    PDF = 'pdf'
    IMAGE = 'image'
    EXECUTABLE = 'executable'
    CSV = 'csv'
    TSV = 'tsv'
    JSON = 'json'
    DIRECTORY = 'directory'
    CLOUD_STORAGE = 'cloud-storage'
