class IAMPolicies:
    CAN_VIEW_OTHERS_OPERATIONS = 1 << 0
    CAN_VIEW_OTHERS_WORKFLOWS = 1 << 1
    CAN_VIEW_OPERATIONS = 1 << 2
    CAN_VIEW_WORKFLOWS = 1 << 3

    CAN_CREATE_OPERATIONS = 1 << 4
    CAN_CREATE_WORKFLOWS = 1 << 5

    CAN_MODIFY_OTHERS_WORKFLOWS = 1 << 6

    CAN_RUN_WORKFLOWS = 1 << 7

    CAN_CONTROL_POLICIES = 1 << 8


class OperationViewSetting:
    KIND_AND_TITLE = 'KIND_AND_TITLE'
    TITLE_AND_DESCRIPTION = 'TITLE_AND_DESCRIPTION'
